-- Run this once in Supabase SQL Editor.
create table if not exists public.prediction_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  generated_at timestamptz not null default now(),
  payload jsonb not null
);

alter table public.prediction_snapshots enable row level security;

-- No browser policy is intentionally added. The website reads/writes this table only
-- through the Render server using SUPABASE_SERVICE_ROLE_KEY after verifying the user's JWT.

create index if not exists prediction_snapshots_generated_at_idx
  on public.prediction_snapshots (generated_at desc);
