create table if not exists public.prediction_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  generated_at timestamptz not null default now(),
  payload jsonb not null
);
alter table public.prediction_snapshots enable row level security;
create index if not exists prediction_snapshots_generated_at_idx
  on public.prediction_snapshots (generated_at desc);
