import {num,pct,avg,MIN_LEAGUE_GAMES,MIN_SPLIT_TABLE_SAMPLE,MIN_SPLIT_FORM_SAMPLE,SPLIT_LONG_SAMPLE} from './engineConfig.js'
function rowsForGroup(standings,teamId){const rows=Array.isArray(standings)?standings:[],own=rows.find(r=>String(r?.team?.id)===String(teamId)),gi=own?._s2pGroupIndex;if(gi===null||gi===undefined)return rows;const g=rows.filter(r=>r?._s2pGroupIndex===gi);return g.length?g:rows}
const overallPlayed=row=>Math.max(0,num(row?.all?.played)??0)
export function leagueMature(standings,homeId,awayId){if(!Array.isArray(standings)||!standings.length)return false;const min=Math.min(...standings.map(overallPlayed)),h=standings.find(r=>String(r?.team?.id)===String(homeId)),a=standings.find(r=>String(r?.team?.id)===String(awayId));return min>=MIN_LEAGUE_GAMES&&overallPlayed(h)>=MIN_LEAGUE_GAMES&&overallPlayed(a)>=MIN_LEAGUE_GAMES}
function record(row,venue){const r=row?.[venue]||{},played=Math.max(0,num(r.played)??0),win=Math.max(0,num(r.win)??0),draw=Math.max(0,num(r.draw)??0),lose=Math.max(0,num(r.lose)??0),gf=num(r.goals?.for),ga=num(r.goals?.against),points=win*3+draw,gd=gf!==null&&ga!==null?gf-ga:null;return{played,win,draw,lose,gf,ga,points,ppg:played?points/played:null,gd,gdpg:played&&gd!==null?gd/played:null,gfpg:played&&gf!==null?gf/played:null,winRate:played?win/played:null}}
const strengthSort=(a,b)=>Number(b.ppg??-999)-Number(a.ppg??-999)||Number(b.gdpg??-999)-Number(a.gdpg??-999)||Number(b.gfpg??-999)-Number(a.gfpg??-999)||Number(b.winRate??-999)-Number(a.winRate??-999)||b.points-a.points||Number(b.gd??-999)-Number(a.gd??-999)||Number(b.gf??-999)-Number(a.gf??-999)||b.win-a.win
export function splitStandingProfile(standings,teamId,venue){const base=rowsForGroup(standings,teamId).map(row=>({id:row?.team?.id,name:row?.team?.name||'',overallPosition:num(row?.rank),...record(row,venue)})).filter(x=>x.id!==null&&x.id!==undefined),ranked=[...base].filter(x=>x.played>0).sort(strengthSort),rank=new Map(ranked.map((x,i)=>[String(x.id),i+1])),row=base.find(x=>String(x.id)===String(teamId));if(!row)return null;const ready=row.played>=MIN_SPLIT_TABLE_SAMPLE;return{venue,position:ready?(rank.get(String(row.id))??null):null,positionSampleReady:ready,leagueSize:base.length,played:row.played,ppg:row.played?+(row.ppg||0).toFixed(2):null,goalsScored:row.played&&row.gf!==null?+(row.gf/row.played).toFixed(2):null,goalsConceded:row.played&&row.ga!==null?+(row.ga/row.played).toFixed(2):null,seasonWinRate:row.played?pct(row.win,row.played):null,seasonLossRate:row.played?pct(row.lose,row.played):null,overallPosition:row.overallPosition}}
const finished=f=>['FT','AET','PEN'].includes(String(f?.fixture?.status?.short||''))
const atVenue=(f,id,v)=>v==='home'?String(f?.teams?.home?.id)===String(id):String(f?.teams?.away?.id)===String(id)
function goals(f,id){const h=num(f?.goals?.home),a=num(f?.goals?.away);if(h===null||a===null)return null;return String(f?.teams?.home?.id)===String(id)?{own:h,opp:a,total:h+a}:{own:a,opp:h,total:h+a}}
export function recentVenueProfile(fixtures,id,venue){const rows=(Array.isArray(fixtures)?fixtures:[]).filter(f=>finished(f)&&atVenue(f,id,venue)&&goals(f,id)).sort((a,b)=>new Date(b?.fixture?.date)-new Date(a?.fixture?.date)).slice(0,SPLIT_LONG_SAMPLE),last5=rows.slice(0,5),s5=last5.length>=MIN_SPLIT_FORM_SAMPLE?last5:[],s10=rows.length>=SPLIT_LONG_SAMPLE?rows:[],gr=rows.length>=MIN_SPLIT_FORM_SAMPLE?rows:[],rate=(set,fn)=>set.length?pct(set.filter(fn).length,set.length):null,wr=rate(s5,f=>goals(f,id).own>goals(f,id).opp),lr=rate(s5,f=>goals(f,id).own<goals(f,id).opp),wr10=rate(s10,f=>goals(f,id).own>goals(f,id).opp),lr10=rate(s10,f=>goals(f,id).own<goals(f,id).opp),metric=fn=>rate(gr,fn),o15=metric(f=>goals(f,id).total>1.5),o25=metric(f=>goals(f,id).total>2.5),o35=metric(f=>goals(f,id).total>3.5);let agreement='INSUFFICIENT';if(s10.length){if(wr>=60&&wr10>=60)agreement='WIN_STRONG';else if(lr>=60&&lr10>=60)agreement='LOSS_STRONG';else if((wr>=60&&wr10<50)||(lr>=60&&lr10<50))agreement='CONFLICT';else agreement='NEUTRAL'}return{formSample:last5.length,goalsSample:gr.length,winRate:wr,lossRate:lr,winRate10:wr10,lossRate10:lr10,formAgreement:agreement,over15:o15,under15:o15===null?null:100-o15,over25:o25,under25:o25===null?null:100-o25,over35:o35,under35:o35===null?null:100-o35,bttsRate:metric(f=>goals(f,id).own>0&&goals(f,id).opp>0),cleanSheetRate:metric(f=>goals(f,id).opp===0),failedToScoreRate:metric(f=>goals(f,id).own===0),recentGoalsScored:avg(gr.map(f=>goals(f,id).own)),recentGoalsConceded:avg(gr.map(f=>goals(f,id).opp))}}
export function makeTeamProfile({standings,history,team,venue}){return{id:team.id,name:team.name,logo:team.logo||null,venue,...(splitStandingProfile(standings,team.id,venue)||{}),...recentVenueProfile(history,team.id,venue)}}
